const fs=require('fs');
const path=require('path');
const root=__dirname;
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const engine=read('three.module.js');
const match=engine.match(/export\s*\{([\s\S]*?)\};?\s*$/);
if(!match)throw Error('Three.js export format not recognized');
const entries=match[1].split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const parts=x.split(/\s+as\s+/);return parts.length===2?`${parts[1]}: ${parts[0]}`:x;});
const embedded=`const THREE = (() => {\n${engine.slice(0,match.index)}\nreturn {${entries.join(',')}};\n})();\n`;
const stripImports=text=>text.replace(/^import .*?;\s*$/gm,'');
const config=`const Config = (() => {${read('config.js').replace('export const Config', 'const Config')}\nreturn Config;})();\n`;
const rules=`const Rogue = (() => {${stripImports(read('rogue.js')).replace(/export const Rogue\s*=/, 'const Rogue =')}\nreturn Rogue;})();\n`;
const expedition=`const createExpedition = (() => {${stripImports(read('expedition.js')).replace('export function createExpedition','function createExpedition')}\nreturn createExpedition;})();\n`;
const game=stripImports(read('main.js'));
const script=(embedded+config+rules+expedition+game).replace(/<\/script/gi,'<\\/script');
const html=read('index.html').replace('<link rel="stylesheet" href="./styles.css">',`<style>${read('styles.css')}</style>`).replace('<script type="module" src="./main.js"></script>',()=>`<script type="module">${script}</script>`).replace('href="./index.html" aria-label="DUNG 小小推球家首页"','href="#" onclick="location.reload();return false" aria-label="DUNG 小小推球家首页"');
const output=path.join(root,'小小推球家-生命远征.html');
fs.writeFileSync(output,html);console.log(JSON.stringify({output,bytes:Buffer.byteLength(html)}));
const tuningScript=(config+stripImports(read('tuning.js'))).replace(/<\/script/gi,'<\\/script');
const tuningHtml=read('tuning.html').replace('<link rel="stylesheet" href="./tuning.css">',()=>`<style>${read('tuning.css')}</style>`).replace('<script type="module" src="./tuning.js"></script>',()=>`<script type="module">${tuningScript}</script>`);
const tuningOutput=path.join(root,'数值调参台.html');
fs.writeFileSync(tuningOutput,tuningHtml);console.log(JSON.stringify({output:tuningOutput,bytes:Buffer.byteLength(tuningHtml)}));
