const { chromium } = require('C:/Users/Admini/.workbuddy/binaries/node/workspace/node_modules/playwright');
const fs = require('fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/?test=1');await page.waitForFunction(()=>window.__game);
 await page.waitForTimeout(1800);await page.screenshot({path:'D:/cxm/疯狂屎壳郎/outputs/preview-home.png'});
 const tests=[];const check=(name,pass,detail='')=>{tests.push({name,pass:!!pass,detail});if(!pass)console.error('FAIL',name,detail);};
 await page.click('#helpBtn');check('玩法说明打开',await page.locator('#helpModal').isVisible());await page.click('#helpClose');
 await page.click('#startBtn');await page.waitForTimeout(400);check('开始游戏',await page.evaluate(()=>__game.state.mode==='playing'&&__game.state.time<150));
 const before=await page.evaluate(()=>({x:__game.state.x,z:__game.state.z}));await page.keyboard.down('KeyW');await page.waitForTimeout(900);await page.keyboard.up('KeyW');
 const after=await page.evaluate(()=>({x:__game.state.x,z:__game.state.z}));check('键盘实际移动',Math.hypot(after.x-before.x,after.z-before.z)>1,JSON.stringify({before,after}));
 await page.keyboard.press('Space');await page.waitForTimeout(110);check('跳跃离地',await page.evaluate(()=>__game.state.y>.1));await page.waitForTimeout(850);
 await page.keyboard.down('KeyD');await page.keyboard.down('Shift');await page.waitForTimeout(500);await page.keyboard.up('Shift');await page.keyboard.up('KeyD');check('冲刺消耗体力',await page.evaluate(()=>__game.state.stamina<99));
 await page.keyboard.press('Escape');const paused=await page.evaluate(()=>__game.state.time);await page.waitForTimeout(300);check('暂停冻结倒计时',await page.evaluate(t=>__game.state.mode==='paused'&&__game.state.time===t,paused));await page.click('#resumeBtn');
 check('采集增长',await page.evaluate(()=>{const g=__game;g.state.y=0;g.state.vy=0;g.state.speed=0;const p=g.pickups.find(p=>p.active&&!p.gold);g.state.x=p.x;g.state.z=p.z;const m=g.state.mass;g.simulate(.001,10);return g.state.mass>m&&g.state.collected>0;}));
 check('金色孢子恢复体力',await page.evaluate(()=>{const g=__game,p=g.pickups.find(p=>p.active&&p.gold);Object.assign(g.state,{x:p.x,z:p.z,y:0,vy:0,speed:0,stamina:20});g.simulate(.001,10);return g.state.stamina===100;}));
 check('敌方碰撞损失质量',await page.evaluate(()=>{const g=__game;Object.assign(g.state,{x:20,z:0,y:0,vy:0,speed:0,mass:6,invincible:0});Object.assign(g.enemies[0],{x:20,z:0});g.simulate(.001,10);return g.state.mass<6&&g.state.invincible>0;}));
 check('蘑菇弹跳',await page.evaluate(()=>{const g=__game;Object.assign(g.state,{x:5,z:3,y:0,vy:0,speed:0});g.simulate(.001,10);return g.state.vy>8;}));
 check('三次交付触发胜利',await page.evaluate(()=>{const g=__game;for(let i=0;i<3;i++){Object.assign(g.state,{x:0,z:-10,y:0,vy:0,speed:0,mass:8,invincible:3});g.simulate(.001,10);}return g.state.delivered===3&&g.state.mode==='ended'&&g.state.score>=2400;}));
 check('胜利结算显示',await page.locator('#endModal').isVisible());await page.screenshot({path:'D:/cxm/疯狂屎壳郎/outputs/preview-victory.png'});
 await page.click('#againBtn');check('重新开始重置',await page.evaluate(()=>__game.state.delivered===0&&__game.state.mass===1&&__game.state.mode==='playing'));
 await page.waitForTimeout(1300);await page.screenshot({path:'D:/cxm/疯狂屎壳郎/outputs/preview-game.png'});
 check('时间耗尽触发结算',await page.evaluate(()=>{__game.state.time=.001;__game.simulate(.01,10);return __game.state.mode==='ended'&&__game.state.time===0;}));
 await page.click('#homeBtn');check('回到首页',await page.locator('#home').isVisible());
 await page.click('#soundBtn');check('静音切换',await page.evaluate(()=>!__game.state.sound));await page.click('#qualityBtn');check('省电画质切换',await page.evaluate(()=>!__game.renderer.shadowMap.enabled));
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);await page.screenshot({path:'D:/cxm/疯狂屎壳郎/outputs/preview-mobile.png'});
 await page.click('#startBtn');await page.waitForTimeout(700);check('移动端摇杆显示',await page.locator('#joystick').isVisible());await page.screenshot({path:'D:/cxm/疯狂屎壳郎/outputs/preview-mobile-game.png'});
 check('移动端没有横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));
 check('无脚本异常',errors.length===0,errors.join('\n'));
 const rendering=await page.evaluate(()=>({calls:__game.renderer.info.render.calls,triangles:__game.renderer.info.render.triangles}));
 const result={passed:tests.filter(t=>t.pass).length,total:tests.length,errors,rendering,tests};fs.writeFileSync('D:/cxm/疯狂屎壳郎/outputs/test-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();if(tests.some(t=>!t.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
